### PR TITLE
Fix pending channel aliases

### LINKED ISSUE #1747: Display of Pending Channels wrong
### Describe the bug

When showing "Pending Channels", Zeus displays multiple times the same Name, which is wrong.
When I click on it, I see the wrong Name with correct pubkey, etc.
Screenshot_2023-10-07-15-57-13-374_app zeusln zeus

### Reproduce

Open multiple channels in own LND Node and see the "Pending channels" tab.

### Zeus version

v0.7.7

### Node interface

LND (REST)

### Network

Clearnet

### Device

Xiaomi Mi Note 10 Lite

### Device operating system

Android 12

### Log output

_No response_

### PR DESCRIPTION
**Pull request by myxmaster**
# Description

This fixes #1747.

Since the aliases of channels was based on their ids and pending channels do not have an id yet, all pending channels got the same alias. Fixes this by determining the alias based on the remote pub key instead. Also refactored channelId so that it might be undefined if channel is pending.

This is based on #1739.

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [x] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Review by shubhamkmr04 — COMMENTED** [review]
tACK

File: android/app/src/main/java/com/zeus/MainApplication.java [hunk 1]
```diff
@@ -79,5 +82,20 @@ public void onCreate() {
...
+
+      @Override
+      public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {
+      }
+
+      @Override
+      public java.security.cert.X509Certificate[] getAcceptedIssuers() {
+        return new java.security.cert.X509Certificate[]{};
+      }
+    };
```
Comment (kaloudis) [inline android/app/src/main/java/com/zeus/MainApplication.java:99]: why are these changes needed?

Comment (kaloudis) [reply android/app/src/main/java/com/zeus/MainApplication.java:99]: @myxmaster have you tested this with cert verification on and off and with self-signed certs?
