### PR TITLE
Fix node connection issues

### LINKED ISSUE #1479: Sometimes updated node settings need app restart to make it work
### Describe the bug

When certain node settings are changed (and saved), it seems Zeus doesn't use the new parameters to connect to the node. After a Zeus restart, it works.

### Reproduce

Add a working node connection via LND (REST) and Tor, save and connect. Go to this node configuration and use button "COPY NODE CONFIG". Edit "Host" to a working clearnet host (e.g. local IP), but leave "Use Tor" toggle enabled. Save config and connect. Obviously it won't work. Now edit this new config and disable Tor and certificate, save and connect. Zeus still won't connect (Error: SOCKS server general failure). After Zeus restart, it works.

Obviously it should work immediately after Tor and certificate is disabled.

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

### Log output

_No response_

### LINKED ISSUE #1492: When connection method is changed while Zeus is trying to connect, old connection establishment is not canceled
### Describe the bug

see title

### Reproduce

- setup 2 connection methods, a working one e.g. `LND (REST) via local network` and a broken one e.g. `LND (REST) via Tor` with a wrong onion address
- pick LND (REST) via Tor as node (although it doesn't work)
- restart Zeus and immediately change connection method to `LND (REST) via local network` (while Zeus is trying to establish connection via Tor)

-> now the connection to node `LND (REST) via local network` will be established and after some time you still see an error because connection via Tor failed...

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

### Log output

_No response_

### PR DESCRIPTION
**Pull request by myxmaster**
# Description

This fixes #1492 and fixes #1479.

#1479 was caused by cached backend calls being used although the node config was changed. So the calls are now removed when reconnecting to a node.

#1492 was due to results of older requests being received and processed after the results of newer requests. Now, results of non-latest requests are generally discarded.

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [x] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Review by shubhamkmr04 — COMMENTED** [review]
The PR resolved the issue [1492](https://github.com/ZeusLN/zeus/issues/1492), was not able to re-create [1479](https://github.com/ZeusLN/zeus/issues/1479)

**Comment by myxmaster** [comment]
Just checked again with v0.7.7-beta2 and #1479 is still reproducible. Did you follow the steps to reproduce 100% @shubhamkmr04 ?

In my opinion this PR still solves both issues and should be merged.

File: stores/SettingsStore.ts [hunk 1]
```diff
@@ -1026,6 +1026,7 @@ export default class SettingsStore {
         if (status) {
             this.error = false;
             this.errorMsg = '';
+            BackendUtils.clearCachedCalls();
```
Comment (kaloudis) [inline stores/SettingsStore.ts:1029]: we should probably check first if `clearCachedCalls` is defined as it isn't defined for all backends

File: stores/NodeInfoStore.ts [hunk 2]
```diff
@@ -38,12 +38,18 @@ export default class NodeInfoStore {
...
+    private static currentRequest: any;
+
     @action
     public getNodeInfo = () => {
         this.errorMsg = '';
         this.loading = true;
+        const currentRequest = (NodeInfoStore.currentRequest = {});
         BackendUtils.getMyNodeInfo()
             .then((data: any) => {
+                if (NodeInfoStore.currentRequest !== currentRequest) {
```
Comment (kaloudis) [inline stores/NodeInfoStore.ts:50]: could you explain the logic here? I don't see currentRequest getting redefined. Just on line 47

File: stores/SettingsStore.ts (hunk 1 above)
Comment (myxmaster) [reply stores/SettingsStore.ts:1029]: That is not necessary since the call function of BackendUtils already checks this.

File: stores/NodeInfoStore.ts [hunk 3]
```diff
@@ -38,12 +38,18 @@ export default class NodeInfoStore {
         this.loading = true;
     };
 
+    private static currentRequest: any;
+
     @action
     public getNodeInfo = () => {
         this.errorMsg = '';
         this.loading = true;
+        const currentRequest = (NodeInfoStore.currentRequest = {});
```
[the remark this answers is not in the document]
Comment (myxmaster) [reply stores/NodeInfoStore.ts]: It is `NodeInfoStore.currentRequest` because the property is static. Static properties cannot be accessed using `this.`. My idea was to make it static to discard responses even if there are multiple instances of `NodeInfoStore` (which should never be the case).

But I realized that this makes no sense since even if there were multiple instances, they all have their own state and then they should also have their own `currentRequest` object.

**Review by kaloudis — APPROVED** [review]
uTACK
