### PR TITLE
fix: menu BackendUtils.supportOffers() is async

### LINKED ISSUE #2895: Menu: BackendUtils.supportOffers() is async
https://github.com/ZeusLN/zeus/blob/cb144f5800031f640a71afe5839e6d7514430cef/views/Menu.tsx#L521

We should probably save the result while connecting, so we don't need to do a backend call when opening the menu...

### PR DESCRIPTION
**Pull request by ajaysehwal**
# Description

Relates to issue: **ZEUS-0000** #2895 

_Please enter a description and screenshots, if appropriate, of the work covered in this PR_
Updates:
Saving the result while connecting, so we don't need to do a backend call when opening the menu again.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [x] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [ ] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [ ] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [ ] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [x] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (CLNRest)
- [ ] Nostr Wallet Connect
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

File: stores/NodeInfoStore.ts [hunk 1]
```diff
@@ -77,6 +78,7 @@ export default class NodeInfoStore {
                         this.regtest = nodeInfo.isRegTest;
                         this.loading = false;
                         this.error = false;
+                        this.supportsOffers = BackendUtils.supportsOffers();
```
Comment (kaloudis) [inline stores/NodeInfoStore.ts:81]: let's clear this on `reset`

**Review by kaloudis — CHANGES_REQUESTED** [review]

File: stores/NodeInfoStore.ts (hunk 1 above)
Comment (ajaysehwal) [reply stores/NodeInfoStore.ts:81]: sure

**Comment by kaloudis** [comment]
LGTM - can you test this against CLNRest and LND REST at minimum?

**Review by shubhamkmr04 — COMMENTED** [review]
Can we maybe use this in other places as well, like the Send view, instead of calling BackendUtils there?

**Comment by ajaysehwal** [comment]
> Can we maybe use this in other places as well, like the Send view, instead of calling BackendUtils there?

ok

**Comment by ajaysehwal** [comment]
Hi @shubhamkmr04, could you please review again?

File: views/Send.tsx [hunk 2]
```diff
@@ -64,6 +64,7 @@ import Contact from '../models/Contact';
 import TransactionRequest, {
     AdditionalOutput
 } from '../models/TransactionRequest';
+import { nodeInfoStore } from '../stores/storeInstances';
```
Comment (shubhamkmr04) [inline views/Send.tsx:67]: NodeInfoStore is already imported above.

**Comment by shubhamkmr04** [comment]
Let's use the NodeInfoStore as we define and use other stores across all views.

**Comment by ajaysehwal** [comment]
Hi @shubhamkmr04 can you please seen my message on slack regarding 3 rd project

**Comment by kaloudis** [comment]
> Hi @shubhamkmr04 can you please seen my message on slack regarding 3 rd project

this is not pertinent to the PR

**Comment by kaloudis** [comment]
Will either have you rebase on top of this PR or wait for it to be merged: https://github.com/ZeusLN/zeus/pull/3026

**Comment by ajaysehwal** [comment]
> Will either have you rebase on top of this PR or wait for it to be merged: #3026

ok, I will rebase and make changes again properly

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/3009 has been merged. Please rebase.

**Review by kaloudis — CHANGES_REQUESTED** [review]
https://github.com/ZeusLN/zeus/pull/3026 has been merged. Please rebase.

**Comment by ajaysehwal** [comment]
> #3026 has been merged. Please rebase.

Already rebased, I'm just making some changes, I will commit updates in some time

File: views/Send.tsx [hunk 3]
```diff
@@ -1468,7 +1468,9 @@ export default class Send extends React.Component<SendProps, SendState> {
                             <Button
                                 title={localeString('general.proceed')}
                                 onPress={async () => await this.payBolt12()}
-                                disabled={!BackendUtils.supportsOffers()}
+                                disabled={
+                                    !this.props.NodeInfoStore.supportsOffers
```
Comment (kaloudis) [inline views/Send.tsx:1472]: you use `this.props.NodeInfoStore` four times. Please destructure it.

**Review by kaloudis — CHANGES_REQUESTED** [review]

**Review by shubhamkmr04 — COMMENTED** [review]
LGTM

**Review by kaloudis — APPROVED** [review]
tACK
