### PR TITLE
Keep navigation state when resuming from background and login is required

### LINKED ISSUE #1880: Adding photo to contact not possible with setting "Require login after app returns from background"
### Describe the bug

If you try to add a photo to a contact while "Require login after app returns from background" is enabled, Zeus will ask for PIN/Password/Biometrics when you come back from picking the photo from your phone. After you logged in, Zeus displays the default view (Balance or Keypad pane) and not the screen where you tried to add a photo, and of course the photo is not saved.

### Reproduce

- Set a Pin or Password
- Enable "Require login after app returns from background"
- Go to contacts and try to add a photo to a new or existing contact
-> After relogin Zeus is displaying default view (Balance or Keypad pane) instead of contacts with your photo

### ZEUS version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

### Log output

_No response_

### PR DESCRIPTION
**Pull request by myxmaster**
# Description

This fixes #1880.

In Lockscreen, after successful login, we navigated to Wallet. Also, when going to background, we called `navigation.pop()` to close a possibly open PIN screen. Both caused that the navigation state was lost.

Instead we now call `navigation.pop()` after successful login in Lockscreen and clear the entered pin in PinPad when going to background.

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

File: views/Wallet/Wallet.tsx [hunk 1]
```diff
@@ -225,10 +225,6 @@ export default class Wallet extends React.Component<WalletProps, WalletState> {
             SettingsStore.loginMethodConfigured() &&
             loginBackground
         ) {
-            // In case the lock screen is visible and a valid PIN is entered and home button is pressed,
-            // unauthorized access would be possible because the PIN is not cleared on next launch.
-            // By calling pop, the lock screen is closed to clear the PIN.
-            this.props.navigation.pop();
```
Comment (shubhamkmr04) [inline views/Wallet/Wallet.tsx:231]: Fixed the issue but now we are having the issue as described in the comments here, we can come back to the zeus after typing in the password and it will still be there

Comment (shubhamkmr04) [reply views/Wallet/Wallet.tsx:231]: that's happening with passphrases in both android and iOS emulator




https://github.com/ZeusLN/zeus/assets/50761978/2f66a78b-50b9-4199-b984-844282dbcbe4
